<?php

namespace craft\web\assets\craftcms;

use Craft;
use craft\web\AssetBundle;
use craft\web\View;

/**
 * Craft Cms asset bundle
 */
class CraftCmsAsset extends AssetBundle
{
    public $sourcePath = __DIR__ . '/src';
    public $depends = [];
    public $js = [
        ['craftcms.js', 'type' => 'module'],
    ];
    public $css = [];

    public function registerAssetFiles($view)
    {
        parent::registerAssetFiles($view); // TODO: Change the autogenerated stub

        $view = Craft::$app->getView();
        if ($view instanceof View) {
            $view->registerJsImport('@craftcms/craftcms', $view->getAssetManager()->getAssetUrl($this, 'craftcms.js', false));
        }
    }
}
